//for testing
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

//real code
export const SET_PLACE = 'SET_PLACE';
export const SET_TIME = 'SET_TIME';

export const EDITABLE_IDEA_SET_TIME = 'EDITABLE_IDEA_SET_TIME';

export const NEW_IDEA_SET_MIN_TIME = "SET_MIN_TIME";
export const NEW_IDEA_SET_MAX_TIME = "SET_MAX_TIME";
export const EDITABLE_IDEA_SET_PLACE = "EDITABLE_IDEA_SET_PLACE";
export const EDITABLE_IDEA_SET_MIN_PEOPLE = "EDITABLE_IDEA_SET_MIN_PEOPLE";
export const EDITABLE_IDEA_SET_MAX_PEOPLE = "EDITABLE_IDEA_SET_MAX_PEOPLE";
export const EDITABLE_IDEA_SET_TITLE = "EDITABLE_IDEA_SET_TITLE";
export const EDITABLE_IDEA_SET_CONTENT = "EDITABLE_IDEA_SET_CONTENT";
export const EDITABLE_IDEA_SET_ID = "EDITABLE_IDEA_SET_ID";

export const SAVE_IDEAS = "SAVE_IDEAS";

export const SEARCH_SET_PLACE = "SEARCH_SET_PLACE";
export const SEARCH_SET_TIME = "SEARCH_SET_TIME";
export const SEARCH_SET_NUM_OF_PEOPLE = "SEARCH_SET_NUM_OF_PEOPLE";
export const SEARCH_SET_MORE = "SEARCH_SET_MORE";

export const CHANGE_PAGE_TO_SHOW_USER = "CHANGE_PAGE_TO_SHOW_USER";
export const CHANGE_PAGE_TO_CREATE_IDEA = "CHANGE_PAGE_TO_CREATE_IDEA";
export const CHANGE_PAGE_TO_SHOW_IDEAS = "CHANGE_PAGE_TO_SHOW_IDEAS";

// export const USER_SET_LIKED_IDEAS = "USER_SET_LIKED_IDEAS";
export const USER_SET_CREATED_IDEAS = "USER_SET_CREATED_IDEAS";
export const USER_SET_DONE_IDEAS = "USER_SET_DONE_IDEAS";

export const UPDATE_CURRENT_IDEA = "UPDATE_CURRENT_IDEA";
export const SET_LOGGED_IN_USER_ID = "SET_LOGGED_IN_USER_ID";
export const SET_LOGGED_IN_USER_FIRST_NAME = "SET_LOGGED_IN_USER_FIRST_NAME";
export const SET_LOGGED_IN_USER_LAST_NAME = "SET_LOGGED_IN_USER_LAST_NAME";

export const CHANGE_CURRENT_IDEA_INDEX = "CHANGE_CURRENT_IDEA_INDEX";

export const ADD_TIME = "ADD_TIME";
export const UPDATE_CREATED_IDEA_IN_USER = "UPDATE_CREATED_IDEA_IN_USER";

export const REDUCE_DIFFICULTY = "ADD_EASY_TO_IDEA";

export const ADD_USER_ID_TO_IDEA_LIKES = "ADD_USER_ID_TO_IDEA_LIKES";
export const ADD_USER_TO_IDEA_DISLIKES = "ADD_USER_TO_IDEA_DISLIKES";

export const ADD_LIKED_IDEA_TO_USER = "ADD_LIKED_IDEA_TO_USER";
export const ADD_DISLIKED_IDEA_TO_USER = "ADD_DISLIKED_IDEA_TO_USER";

export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";

export const ADD_ITEM = "ADD_ITEM";

export const ADD_USER_TO_IDEA_ADDED_HARD = "ADD_USER_TO_IDEA_ADDED_HARD";
export const ADD_USER_TO_IDEA_ADDED_EASY = "ADD_USER_TO_IDEA_ADDED_EASY";

export const ADD_USER_TO_IDEA_ADDED_LONG = "ADD_USER_TO_IDEA_ADDED_LONG";
export const ADD_USER_TO_IDEA_ADDED_SHORT = "ADD_USER_TO_IDEA_ADDED_SHORT";

export const SET_CURRENT_IDEA = "SET_CURRENT_IDEA";
export const USER_PAGE_IDEAS_TYPE = "USER_PAGE_IDEAS_TYPE";

export const CREATE_IDEA = "CREATE_IDEA";

export const ADD_CREATED_IDEA_TO_USER = "ADD_CREATED_IDEA_TO_USER";

export const SET_USER_PREVIEW_IDEA = "SET_USER_PREVIEW_IDEA";
export const USER_SET_LIKED_IDEAS = "USER_SET_LIKED_IDEAS";

export const SET_USER_CREATED_IDEAS = "SET_USER_CREATED_IDEAS";

export const SET_USER_CURRENT_PREVIEWED_IDEAS = "SET_USER_CURRENT_PREVIEWED_IDEAS";

export const USER_SET_SELECTED_DROPDOWN_TYPE = "USER_SET_SELECTED_DROPDOWN_TYPE";

export const SET_USER_CURRENT_PREVIEWED_IDEA_IS_EDIT = "SET_USER_CURRENT_PREVIEWED_IDEA_IS_EDIT";
export const SET_USER_CURRENT_PREVIEWED_IDEA = "SET_USER_CURRENT_PREVIEWED_IDEA";

export const PREVIEWED_IDEA_SET_TITLE = "PREVIEWED_IDEA_SET_TITLE";

export const PREVIEWED_IDEA_SET_CONTENT = "PREVIEWED_IDEA_SET_CONTENT";
export const UPDATE_PREVIEWED_IDEAS = "UPDATE_PREVIEWED_IDEAS";
export const UPDATE_CREATED_IDEAS_IDEA = "UPDATE_CREATED_IDEAS_IDEA";
export const UPDATE_LIKED_IDEAS_IDEA = "UPDATE_LIKED_IDEAS_IDEA";

export const USER_COPY_CREATED_IDEAS_TO_CURRENT_IDEAS = "USER_COPY_CREATED_IDEAS_TO_CURRENT_IDEAS";
export const USER_COPY_LIKED_IDEAS_TO_CURRENT_IDEAS = "USER_COPY_LIKED_IDEAS_TO_CURRENT_IDEAS";
export const CHANGE_UPDATE_TOGGLE = "CHANGE_UPDATE_TOGGLE";

export const SET_USER_LIKED_IDEAS = "SET_USER_LIKED_IDEAS";
export const CLEAR_EDITABLE_IDEA = "CLEAR_EDITABLE_IDEA";

export const EDITABLE_IDEA_SET_TAGS = "EDITABLE_IDEA_SET_TAGS";

export const CHANGE_SEARCHED_STATE = "CHANGE_SEARCHED_STATE";

export const CHANGE_LOGGED_IN_STATE = "CHANGE_LOGGED_IN_STATE";
export const CHANGE_SHOW_LOGIN_STATE = "CHANGE_SHOW_LOGIN_STATE";

export const UPDATE_USER_CREATED_IDEA = "UPDATE_USER_CREATED_IDEA";
export const REMOVE_CREATED_IDEA_FROM_USER = "REMOVE_CREATED_IDEA_FROM_USER";
export const CLEAR_USER_PAGE_IDEA = "CLEAR_USER_PAGE_IDEA";
export const UPDATE_USER_CURRENT_PREVIEWED_IDEAS = "UPDATE_USER_CURRENT_PREVIEWED_IDEAS";

export const EMPTY_USER_PREVIEWED_IDEA = "EMPTY_USER_PREVIEWED_IDEA";
// export const ADD_USER_TO_LIKED_OF_CREATED_IDEA = "ADD_USER_TO_LIKED_OF_CREATED_IDEA";

export const REMOVE_IDEA_LIKED = "REMOVE_IDEA_LIKED";
export const REMOVE_IDEA_DISLIKED = "REMOVE_IDEA_DISLIKED";
export const REMOVE_USER_FROM_IDEA_LIKES = "REMOVE_USER_FROM_IDEA_LIKES";
export const REMOVE_USER_FROM_IDEA_DISLIKES = "REMOVE_USER_FROM_IDEA_DISLIKES";
export const REMOVE_USER_FROM_IDEA_ADDED_HARD = "REMOVE_USER_FROM_IDEA_ADDED_HARD";
export const REMOVE_USER_FROM_IDEA_ADDED_EASY = "REMOVE_USER_FROM_IDEA_ADDED_EASY";

export const REMOVE_USER_FROM_IDEA_ADDED_LONG = "REMOVE_USER_FROM_IDEA_ADDED_LONG";
export const REMOVE_USER_FROM_IDEA_ADDED_SHORT = "REMOVE_USER_FROM_IDEA_ADDED_SHORT";

export const UPDATE_CURRENT_PREVIEWED_USER_IDEA = "UPDATE_CURRENT_PREVIEWED_USER_IDEA";

export const SET_TOP_LIKED_IDEAS = "SET_TOP_LIKED_IDEAS";
export const SET_TOP_HARD_IDEAS = "SET_TOP_HARD_IDEAS";

export const SET_TOP_TABLE_IS_IDEA_CLICKED = "SET_TOP_TABLE_IS_IDEA_CLICKED";
export const SET_TOP_TABLE_IDEA = "SET_TOP_TABLE_IDEA";

export const SEARCH_SET_SEARCH_MORE_VALIDATION = "SEARCH_SET_SEARCH_MORE_VALIDATION";
export const SEARCH_SET_IS_SEARCHED_STATE = "SEARCH_SET_IS_SEARCHED_STATE";
export const SEARCH_SET_IS_CLICKED_SEARCH = "SEARCH_SET_IS_CLICKED_SEARCH";
export const SEARCH_SET_IS_MORE_DIRTY = "SEARCH_SET_IS_MORE_DIRTY";
export const SEARCH_SET_IS_PLACE_DIRTY = "SEARCH_SET_IS_PLACE_DIRTY";
export const SEARCH_SET_IS_PLACE_VALID = "SEARCH_SET_IS_PLACE_VALID";
export const CREATE_IDEA_SET_TIME = "CREATE_IDEA_SET_TIME";
export const CREATE_IDEA_SET_MIN_PEOPLE = "CREATE_IDEA_SET_MIN_PEOPLE";
export const CREATE_IDEA_SET_MAX_PEOPLE = "CREATE_IDEA_SET_MAX_PEOPLE";

export const UPDATE_EDITABLE_IDEA = "UPDATE_EDITABLE_IDEA";
export const EDITABLE_IDEA_SET_IS_TITLE_VALID = "EDITABLE_IDEA_SET_IS_TITLE_VALID";
export const EDITABLE_IDEA_SET_IS_CONTENT_VALID = "EDITABLE_IDEA_SET_IS_CONTENT_VALID";
export const EDITABLE_IDEA_SET_IS_PLACE_VALID = "EDITABLE_IDEA_SET_IS_PLACE_VALID";
export const EDITABLE_SET_IS_BUTTON_CLICKED_VALUE = "EDITABLE_SET_IS_BUTTON_CLICKED_VALUE";

export const SET_IS_SEARCHING = "SET_IS_SEARCHING";

export const SET_PLACE_SUGGESTIONS = "SET_PLACE_SUGGESTIONS";
export const SET_TAG_SUGGESTIONS = "SET_TAG_SUGGESTIONS";

export const USER_PAGE_SHOW_NEXT_CREATED_IDEA = "USER_PAGE_SHOW_NEXT_CREATED_IDEA";

export const SET_IS_MAIN_LOADING = "SET_IS_MAIN_LOADING";

export const SEARCH_SET_CURRENT_IDEA_BY_ID = "SEARCH_SET_CURRENT_IDEA_BY_ID";
export const ON_CREATE_SET_IS_DUPLICATE_TITLE = "ON_CREATE_SET_IS_DUPLICATE_TITLE";

export const SET_TOP_POPULAR_IDEAS = "SET_TOP_POPULAR_IDEAS";
export const SET_TOP_NEWEST_IDEAS = "SET_TOP_NEWEST_IDEAS";

export const REMOVE_LIKED_IDEA_FROM_USER = "REMOVE_LIKED_IDEA_FROM_USER";

 










