//for testing
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

//real code
export const SET_PLACE = 'SET_PLACE';
export const SET_TIME = 'SET_TIME';

export const NEW_IDEA_SET_TIME = 'NEW_IDEA_SET_TIME';

export const NEW_IDEA_SET_MIN_TIME = "SET_MIN_TIME";
export const NEW_IDEA_SET_MAX_TIME = "SET_MAX_TIME";
export const NEW_IDEA_SET_PLACE = "NEW_IDEA_SET_PLACE";
export const NEW_IDEA_SET_MIN_PEOPLE = "NEW_IDEA_SET_MIN_PEOPLE";
export const NEW_IDEA_SET_MAX_PEOPLE = "NEW_IDEA_SET_MAX_PEOPLE";
export const NEW_IDEA_SET_TITLE = "NEW_IDEA_SET_TITLE";
export const NEW_IDEA_SET_CONTENT = "NEW_IDEA_SET_CONTENT";

export const SAVE_IDEAS = "SAVE_IDEAS";

export const SEARCH_SET_PLACE = "SEARCH_SET_PLACE";
export const SEARCH_SET_TIME = "SEARCH_SET_TIME";
export const SEARCH_SET_NUM_OF_PEOPLE = "SEARCH_SET_NUM_OF_PEOPLE";
export const SEARCH_SET_MORE = "SEARCH_SET_MORE";

export const NO_ITEMS_FOUND = "NO_ITEMS_FOUND";
export const CHANGE_PAGE_TO_SHOW_USER = "CHANGE_PAGE_TO_SHOW_USER";
export const CHANGE_PAGE_TO_CREATE_IDEA = "CHANGE_PAGE_TO_CREATE_IDEA";
export const CHANGE_PAGE_TO_SHOW_IDEAS = "CHANGE_PAGE_TO_SHOW_IDEAS";

export const USER_SET_LIKED_IDEAS = "USER_SET_LIKED_IDEAS";
export const USER_SET_CREATED_IDEAS = "USER_SET_CREATED_IDEAS";
export const USER_SET_DONE_IDEAS = "USER_SET_DONE_IDEAS";



