//for testing
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

//real code
export const SET_PLACE = 'SET_PLACE';
export const SET_TIME = 'SET_TIME';

export const NEW_IDEA_SET_TIME = 'NEW_IDEA_SET_TIME';

export const NEW_IDEA_SET_MIN_TIME = "SET_MIN_TIME";
export const NEW_IDEA_SET_MAX_TIME = "SET_MAX_TIME";
export const NEW_IDEA_SET_PLACE = "NEW_IDEA_SET_PLACE";
export const NEW_IDEA_SET_MIN_PEOPLE = "NEW_IDEA_SET_MIN_PEOPLE";
export const NEW_IDEA_SET_MAX_PEOPLE = "NEW_IDEA_SET_MAX_PEOPLE";
export const NEW_IDEA_SET_TITLE = "NEW_IDEA_SET_TITLE";
export const NEW_IDEA_SET_CONTENT = "NEW_IDEA_SET_CONTENT";

export const SAVE_IDEAS = "SAVE_IDEAS";

export const SEARCH_SET_PLACE = "SEARCH_SET_PLACE";
export const SEARCH_SET_TIME = "SEARCH_SET_TIME";
export const SEARCH_SET_NUM_OF_PEOPLE = "SEARCH_SET_NUM_OF_PEOPLE";
export const SEARCH_SET_MORE = "SEARCH_SET_MORE";

export const NO_ITEMS_FOUND = "NO_ITEMS_FOUND";
export const CHANGE_PAGE_TO_SHOW_USER = "CHANGE_PAGE_TO_SHOW_USER";
export const CHANGE_PAGE_TO_CREATE_IDEA = "CHANGE_PAGE_TO_CREATE_IDEA";
export const CHANGE_PAGE_TO_SHOW_IDEAS = "CHANGE_PAGE_TO_SHOW_IDEAS";

// export const USER_SET_LIKED_IDEAS = "USER_SET_LIKED_IDEAS";
export const USER_SET_CREATED_IDEAS = "USER_SET_CREATED_IDEAS";
export const USER_SET_DONE_IDEAS = "USER_SET_DONE_IDEAS";

export const UPDATE_CURRENT_IDEA = "UPDATE_CURRENT_IDEA";
export const SET_LOGGED_IN_USER_ID = "SET_LOGGED_IN_USER_ID";
export const SET_LOGGED_IN_USER_FIRST_NAME = "SET_LOGGED_IN_USER_FIRST_NAME";
export const SET_LOGGED_IN_USER_LAST_NAME = "SET_LOGGED_IN_USER_LAST_NAME";

export const CHANGE_CURRENT_IDEA_INDEX = "CHANGE_CURRENT_IDEA_INDEX";

export const ADD_TIME = "ADD_TIME";
export const REDUCE_TIME = "REDUCE_TIME";

export const ADD_DIFFICULTY = "ADD_HARD_TO_IDEA";
export const REDUCE_DIFFICULTY = "ADD_EASY_TO_IDEA";

export const ADD_USER_TO_IDEA_LIKES = "ADD_USER_TO_IDEA_LIKES";
export const ADD_USER_TO_IDEA_DISLIKES = "ADD_USER_TO_IDEA_DISLIKES";

export const ADD_LIKED_IDEA_TO_USER = "ADD_LIKED_IDEA_TO_USER";
export const ADD_DISLIKED_IDEA_TO_USER = "ADD_DISLIKED_IDEA_TO_USER";

export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";

export const ADD_ITEM = "ADD_ITEM";

export const ADD_USER_TO_IDEA_ADDED_HARD = "ADD_USER_TO_IDEA_ADDED_HARD";
export const ADD_USER_TO_IDEA_ADDED_EASY = "ADD_USER_TO_IDEA_ADDED_EASY";

export const ADD_USER_TO_IDEA_ADDED_LONG = "ADD_USER_TO_IDEA_ADDED_LONG";
export const ADD_USER_TO_IDEA_ADDED_SHORT = "ADD_USER_TO_IDEA_ADDED_SHORT";

export const SET_CURRENT_IDEA = "SET_CURRENT_IDEA";
export const USER_PAGE_IDEAS_TYPE = "USER_PAGE_IDEAS_TYPE";

export const CREATE_IDEA = "CREATE_IDEA";

export const ADD_CREATED_IDEA_TO_USER = "ADD_CREATED_IDEA_TO_USER";

export const SET_USER_PREVIEW_IDEA = "SET_USER_PREVIEW_IDEA";
export const USER_SET_LIKED_IDEAS_DATA = "USER_SET_LIKED_IDEAS_DATA";

export const SET_USER_CREATED_IDEAS = "SET_USER_CREATED_IDEAS";

export const SET_USER_CURRENT_PREVIEWD_IDEAS = "SET_USER_CURRENT_PREVIEWD_IDEAS";








