export const idea = {
    title: "",
    content: "",
    date: {},
    createdIn: "",
    createdBy: "",
    subjects: [],
    places: [],
    time: 0,
    createdOn: (Date.now()),
    minNumOfPeople: 0,
    maxNumOfPeople: 0,
    liked: [],
    disliked: [],
}